language: cpp

os:
  - windows
  - linux

branches:
  only:
  - master
  except:
  - /^(?i:deploy)-.*$/
  - /^(?i:release)-.*$/

env:
  global:
   - DEPS_DIR=${HOME}/deps
   - VCPKG_ROOT=${DEPS_DIR}/vcpkg
  jobs:
   - BRANCH=1.10-dev
   - BRANCH=master

before_install:
  - git clone https://github.com/alliedmodders/ambuild ${DEPS_DIR}/ambuild
  - git clone https://github.com/Microsoft/vcpkg ${DEPS_DIR}/vcpkg

jobs:
  include:
  - stage: build
    os: linux
    env:
      global:
       - VCPKG_TARGET_TRIPLET=x86-linux-sm
    install:
      - cp ${TRAVIS_BUILD_DIR}/vcpkg_triplet/${VCPKG_TARGET_TRIPLET}.cmake ${DEPS_DIR}/vcpkg/triplets
      - |
        cd ${DEPS_DIR}/ambuild
        python setup.py install
      - |
        cd ${DEPS_DIR}/vcpkg
        ./bootstrap.bat
        ./vcpkg.exe install boost-asio boost-beast openssl jsoncpp --triplet ${VCPKG_TARGET_TRIPLET}
    deploy:
      file:
        - build/package/addons/sourcemod/extensions/kxnrl.message.ext.so

  - stage: build
    os: windows
    env:
      global:
       - VCPKG_TARGET_TRIPLET=x86-windows-sm
    install:
      - cp ${TRAVIS_BUILD_DIR}/vcpkg_triplet/${VCPKG_TARGET_TRIPLET}.cmake ${DEPS_DIR}/vcpkg/triplets
      - choco install -y visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 --add Microsoft.VisualStudio.Component.WinXP";
      - |
        cd ${DEPS_DIR}/ambuild
        python setup.py install
      - |
        cd ${DEPS_DIR}/vcpkg
        ./bootstrap.bat
        ./vcpkg.exe install boost-asio boost-beast openssl jsoncpp --triplet ${VCPKG_TARGET_TRIPLET}
    deploy:
      file:
        - build/package/addons/sourcemod/extensions/kxnrl.message.ext.dll

script:
  - python ./build.py

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Kxnrl"
  - git config --local user.email "kyle@kxnrl.com"
  - export TRAVIS_TAG=deploy-$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $TOKEN
  on:
      condition: "$BRANCH = 1.10-dev"
      repo: Kxnrl/Kxnrl.Message.Extension
      all_branches: true
