language: cpp

branches:
  only:
  - master
  - stable
  except:
  - /^(?i:deploy)-.*$/
  - /^(?i:release)-.*$/

env:
  global:
   - DEPS_DIR=${HOME}/deps

before_install:
  - git clone https://github.com/alliedmodders/ambuild ${DEPS_DIR}/ambuild

jobs:
  include:
  - name: Linux
    dist: bionic
    python: 3.8
    env:
      - BRANCH=1.10-dev
    before_script:
      - sudo apt-get install -y gcc-multilib g++-multilib binutils
      - |
        pushd ${DEPS_DIR}/ambuild
        sudo python3 setup.py install
        popd
      - chmod +x build.sh
    script:
      - ./build.sh

  - name: Windows
    os: windows
    python: 3.8
    env:
      - BRANCH=1.10-dev
      - PATH=/c/Python38:/c/Python38/Scripts:${PATH}
    before_script:
      - choco install -y visualstudio2019buildtools python3 --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
      - |
        pushd ${DEPS_DIR}/ambuild
        python setup.py install
        popd
    script:
      - ./build.bat      

before_deploy:
 # Set up git user name and tag this commit
  - git config --local user.name "Kxnrl"
  - git config --local user.email "kyle@kxnrl.com"
  - export TRAVIS_TAG=deploy-$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $TOKEN
  file:
    - build/package/addons/sourcemod/extensions/kxnrl.message.ext.dll
    - build/package/addons/sourcemod/extensions/kxnrl.message.ext.so
  on:
    condition: "$BRANCH = 1.10-dev"
    repo: Kxnrl/Kxnrl.Message.Extension
    all_branches: true
