language: cpp

branches:
  only:
  - master
  except:
  - /^(?i:deploy)-.*$/
  - /^(?i:release)-.*$/

env:
  global:
   - DEPS_DIR=${HOME}/deps
   - VCPKG_ROOT=${DEPS_DIR}/vcpkg

before_install:
  - git clone https://github.com/alliedmodders/ambuild ${DEPS_DIR}/ambuild
  - git clone https://github.com/Microsoft/vcpkg ${DEPS_DIR}/vcpkg

jobs:
  include:
  - name: Linux
    dist: bionic
    python: 3.8
    env:
      - BRANCH=1.10-dev
      - VCPKG_TARGET_TRIPLET=x86-linux-sm
    before_script:
      - sudo apt-get install -y gcc-multilib g++-multilib
      - cp ${TRAVIS_BUILD_DIR}/vcpkg_triplet/${VCPKG_TARGET_TRIPLET}.cmake ${DEPS_DIR}/vcpkg/triplets
      - |
        pushd ${DEPS_DIR}/ambuild
        sudo python setup.py install
        popd
      - |
        pushd ${VCPKG_ROOT}
        git checkout e3dfd4a9fa25c05abcf166a1b3bb260b542ed598
        ./bootstrap-vcpkg.sh
        ./vcpkg install boost-asio boost-beast jsoncpp openssl --triplet ${VCPKG_TARGET_TRIPLET}
        popd
    script:
      - sudo ./build.sh
    deploy:
      file:
        - build/package/addons/sourcemod/extensions/kxnrl.message.ext.so

  - name: Windows
    os: windows
    python: 3.8
    env:
      - BRANCH=1.10-dev
      - VCPKG_TARGET_TRIPLET=x86-windows-sm
      - PATH=/c/Python38:/c/Python38/Scripts:${PATH}
    before_script:
      - cp ${TRAVIS_BUILD_DIR}/vcpkg_triplet/${VCPKG_TARGET_TRIPLET}.cmake ${DEPS_DIR}/vcpkg/triplets
      - choco install -y visualstudio2017buildtools python3 --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 --add Microsoft.VisualStudio.Component.WinXP";
      - |
        pushd ${DEPS_DIR}/ambuild
        python setup.py install
        popd
      - |
        ${VCPKG_ROOT}/bootstrap-vcpkg.bat
        ${VCPKG_ROOT}/vcpkg.exe install boost-asio boost-beast jsoncpp openssl --triplet ${VCPKG_TARGET_TRIPLET}
    script:
      - ./build.bat
    deploy:
      file:
        - build/package/addons/sourcemod/extensions/kxnrl.message.ext.dll

#before_deploy:
# # Set up git user name and tag this commit
#  - git config --local user.name "Kxnrl"
#  - git config --local user.email "kyle@kxnrl.com"
#  - export TRAVIS_TAG=deploy-$TRAVIS_BUILD_NUMBER
#  - git tag $TRAVIS_TAG

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key: $TOKEN
#  on:
#      condition: "$BRANCH = 1.10-dev"
#      repo: Kxnrl/Kxnrl.Message.Extension
#      all_branches: true
